# Generated by Django 4.0.5 on 2022-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcategory',
            name='color_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colorcategory',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
