# Generated by Django 4.0.5 on 2022-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_bandingcategory_product_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='product.sizecategory'),
        ),
    ]
